# Generated by Django 4.0.5 on 2022-06-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_globalelection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='region',
        ),
        migrations.AlterField(
            model_name='voter',
            name='passport_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
