# Generated by Django 4.0.5 on 2022-06-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_alter_vote_candidate_alter_vote_election_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image_url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
